language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5
    - android-sdk-license-c81a61d9

jdk:
  - oraclejdk7
  - oraclejdk8

script:
  - ./gradlew clean check

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
